IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPR = IJLib.MediaPathRaids
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "th\\"

local TH = {}

TH.Name = IJ_DB_RAID_TH_NAME
TH.Story = IJ_DB_RAID_TH_STORY
TH.Type = IJLib.InstanceType.Raid
TH.Background = IMP .. IMPR .. instanceMediaAcronym .. "background"
TH.GridBackground = IMP .. IMPR .. instanceMediaAcronym .. "grid-background"
TH.MapId = IMI.TimbermawHold
TH.IconScale = 0.7
TH.MinLevel = 60
TH.MaxLevel = 60
TH.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.TimbermawHold,
        MapCoordinateX = 16.8,
        MapCoordinateY = 43.2,
    },
}
TH.Bosses = {
    [1] = { -- NOTE: Missing abilities, Missing loot
        Id = "aaaaa",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "aaaaa" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "aaaaa" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_aaaaa,
        Story = IJ_DB_RAID_TH_BOSS_STORY_aaaaa,
        MapCoordinateX = 31.0,
        MapCoordinateY = 73.5,
		Loot = {
            [1] = {
                Id = "33237",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
            [2] = {
                Id = "33238",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
            [3] = {
                Id = "33239",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
            [4] = {
                Id = "33240",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33241",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33242",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
        },
		
		
    },
    [2] = { -- NOTE: Missing abilities, Missing loot
        Id = "bbbbb",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "bbbbb" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "bbbbb" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_bbbbb,
        Story = IJ_DB_RAID_TH_BOSS_STORY_bbbbb,
        MapCoordinateX = 15.1,
        MapCoordinateY = 59.3,
		Loot = {
			[1] = {
                Id = "33243",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33244",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33245",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33246",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33247",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33248",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
		},
    },
    [3] = { -- NOTE: Missing abilities, Missing loot
        Id = "ccccc",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "ccccc" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "ccccc" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_ccccc,
        Story = IJ_DB_RAID_TH_BOSS_STORY_ccccc,
        MapCoordinateX = 14.7,
        MapCoordinateY = 50.0,
		Loot = {
			[1] = {
                Id = "33249",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33250",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33251",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33252",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33253",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33254",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[7] = {
                Id = "33255",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[8] = {
                Id = "33256",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
		},
    },
    [4] = { -- NOTE: Missing abilities, Missing loot
        Id = "ddddd",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "ddddd" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "ddddd" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_ddddd,
        Story = IJ_DB_RAID_TH_BOSS_STORY_ddddd,
        MapCoordinateX = 32.4,
        MapCoordinateY = 36.3,
		Loot = {
			[1] = {
                Id = "33257",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33258",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33259",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33260",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33261",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33262",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[7] = {
                Id = "33263",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
		},
    },
    [5] = { -- NOTE: Missing abilities, Missing loot
        Id = "eeeee",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "eeeee" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "eeeee" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_eeeee,
        Story = IJ_DB_RAID_TH_BOSS_STORY_eeeee,
        MapCoordinateX = 54.7,
        MapCoordinateY = 64.7,
		Loot = {
			[1] = {
                Id = "33264",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33265",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33266",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33267",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33268",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33269",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[7] = {
                Id = "33270",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
		},
    },
    [6] = { -- NOTE: Missing abilities, Missing loot
        Id = "hhhhh",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "hhhhh" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "hhhhh" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_hhhhh,
        Story = IJ_DB_RAID_TH_BOSS_STORY_hhhhh,
        MapCoordinateX = 42.4,
        MapCoordinateY = 30.7,
		Loot = {
			[1] = {
                Id = "33271",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33272",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33273",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33274",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33275",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33276",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[7] = {
                Id = "33277",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[8] = {
                Id = "33278",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
		},
    },
    [7] = { -- NOTE: Missing abilities, Missing loot
        Id = "iiiii",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "iiiii" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "iiiii" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_iiiii,
        Story = IJ_DB_RAID_TH_BOSS_STORY_iiiii,
        MapCoordinateX = 22.2,
        MapCoordinateY = 8.4,
		Loot = {
			[1] = {
                Id = "33279",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33280",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33281",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33283",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33284",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33285",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[7] = {
                Id = "33286",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
		},
    },
    [8] = { -- NOTE: Missing abilities, Missing loot
        Id = "fffff",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "fffff" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "fffff" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_fffff,
        Story = IJ_DB_RAID_TH_BOSS_STORY_fffff,
        MapCoordinateX = 45.7,
        MapCoordinateY = 58.4,
		Loot = {
			[1] = {
                Id = "33287",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33288",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33289",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33290",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33291",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33292",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },	
		},
    },
    [9] = { -- NOTE: Missing abilities, Missing loot
        Id = "ggggg",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "ggggg" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "ggggg" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_ggggg,
        Story = IJ_DB_RAID_TH_BOSS_STORY_ggggg,
        MapCoordinateX = 49.5,
        MapCoordinateY = 37.8,
		Loot = {			
			[1] = {
                Id = "33295",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33301",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33324",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33325",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33326",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33327",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[7] = {
                Id = "33328",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[8] = {
                Id = "33329",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[9] = {
                Id = "33330",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[10] = {
                Id = "33331",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[11] = {
                Id = "33332",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[12] = {
                Id = "33333",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[13] = {
                Id = "33334",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
		},
    },
    [10] = { -- NOTE: Missing abilities, Missing loot
        Id = "jjjjj",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "jjjjj" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "jjjjj" .. IMPF,
        Name = IJ_DB_RAID_TH_BOSS_NAME_jjjjj,
        Story = IJ_DB_RAID_TH_BOSS_STORY_jjjjj,
        MapCoordinateX = 49.5,
        MapCoordinateY = 37.8,
		Loot = {
			[1] = {
                Id = "33341",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[2] = {
                Id = "33342",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[3] = {
                Id = "33343",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[4] = {
                Id = "33344",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[5] = {
                Id = "33345",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[6] = {
                Id = "33346",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Epic,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			
			
			
			
			[7] = {
                Id = "33361",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[8] = {
                Id = "33362",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[9] = {
                Id = "33363",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
			[10] = {
                Id = "33364",
                Icon = "trade_engineering",
                Name = IJ_LOOT_NAME_33241,
                Quality = IQ.Rare,
                DropChance = 0,
                ClassRestriction = { IMCL.Priest, IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Rogue, IMCL.Shaman, IMCL.Hunter, IMCL.Warrior, IMCL.Paladin, },
            },
		}
    },
}

IJDB.R.TH = TH
